### ISSUE TITLE
Crashes with 30.20

### ISSUE THREAD

**Issue by 7krisp** [notsamicc/UniversalFNConsole#4]
Fatal error: [File:D:\build\++Fortnite\Sync\Engine\Source\Runtime\Core\Private\GenericPlatform\GenericPlatformMemory.cpp] [Line: 253] Ran out of memory allocating 18446744073709551295 (17592186044416.0 MiB) bytes with alignment 0. Last error msg: The operation completed successfully..

**Comment by notsamicc** [comment]
stop spamming my posts
